/* ═══════════════════════════════════════════════════════════
   CONTENIDO LAB — fórmulas de hook y datos de ejemplo.
   Las fórmulas son de la casa (siempre visibles).
   Los ejemplos vienen marcados con ejemplo:true y se pueden
   borrar desde Más → Datos.
   ═══════════════════════════════════════════════════════════ */

const FORMULAS = [
  { id: "f-pregunta", tipo: "pregunta", nombre: "La pregunta incómoda",
    plantilla: "¿Por qué {{tu nicho}} sigue haciendo {{error}} en 2026?",
    ejemplo: "¿Por qué las cafeterías siguen grabando el latte art con luz de techo?" },
  { id: "f-contrarian", tipo: "contrarian", nombre: "Deja de…",
    plantilla: "Deja de {{práctica común}}. Esto es lo que funciona en su lugar.",
    ejemplo: "Deja de poner música trending en todos tus reels. Esto es lo que funciona." },
  { id: "f-resultado", tipo: "resultado", nombre: "Resultado primero",
    plantilla: "Esto es lo que pasa cuando {{acción}} durante {{tiempo}}.",
    ejemplo: "Esto es lo que pasa cuando grabas café con una sola luz de 40W." },
  { id: "f-historia", tipo: "historia", nombre: "El día que…",
    plantilla: "El día que {{momento de quiebre}} entendí {{aprendizaje}}.",
    ejemplo: "El día que un cliente me pidió “que se vea premium” entendí qué es premium de verdad." },
  { id: "f-lista", tipo: "lista", nombre: "Los 3 errores",
    plantilla: "{{N}} errores que cometes al {{actividad}} (el {{número}} lo hace todo el mundo).",
    ejemplo: "3 errores al grabar comida con el celular (el segundo lo hace todo el mundo)." },
  { id: "f-dato", tipo: "dato", nombre: "Dato que rompe",
    plantilla: "El {{porcentaje}} de {{grupo}} {{hecho sorprendente}}. Y nadie habla de esto.",
    ejemplo: "El 80 % de los reels de restaurantes se pierden en los primeros 2 segundos." },
  { id: "f-reto", tipo: "reto", nombre: "En X segundos",
    plantilla: "En {{tiempo}} te muestro cómo {{resultado}} sin {{obstáculo}}.",
    ejemplo: "En 30 segundos te muestro cómo iluminar un plato sin comprar nada." },
  { id: "f-pov", tipo: "pov", nombre: "POV",
    plantilla: "POV: {{situación reconocible de tu audiencia}}.",
    ejemplo: "POV: el cliente dice “hazlo como el video ese que vi”." },
  { id: "f-error", tipo: "error", nombre: "El error silencioso",
    plantilla: "Si tus {{contenido}} no {{resultado deseado}}, es por esto.",
    ejemplo: "Si tus reels no pasan de 300 views, es por esto (y no es el algoritmo)." },
  { id: "f-antes", tipo: "antes", nombre: "Antes / después",
    plantilla: "Grabé lo mismo dos veces: con {{A}} y con {{B}}. Mira la diferencia.",
    ejemplo: "Grabé el mismo corte dos veces: con luz natural y con la Ulanzi. Mira la diferencia." },
  { id: "f-secreto", tipo: "resultado", nombre: "Lo que nadie te dice",
    plantilla: "Lo que nadie te dice de {{tema}}.",
    ejemplo: "Lo que nadie te dice de vivir de hacer videos para marcas." },
  { id: "f-tu", tipo: "pregunta", nombre: "Tú también",
    plantilla: "Si {{situación}}, este video es para ti.",
    ejemplo: "Si tienes un negocio y grabas con el celular, este video es para ti." },
];

const EJEMPLOS = {
  perfil: { nombre: "David", nicho: "creador de contenido audiovisual para marcas de café y carnes en Santander", cuentas: [
    { plataforma: "tiktok", usuario: "@david.contenido" },
    { plataforma: "instagram", usuario: "@david.contenido" },
  ] },
  piezas: [
    { id: "ej-p1", ejemplo: true, titulo: "Cómo grabamos un reel de café en 2 horas", plataforma: "tiktok", formato: "reel", pilar: "Detrás de cámaras",
      hook: "Esto es lo que pasa cuando grabas café con una sola luz de 40W", hookTipo: "resultado", fecha: "2026-08-17", estado: "publicado", duracion: 34,
      guion: "HOOK (0-3s): Esto es lo que pasa cuando grabas café con una sola luz de 40W.\nCONTEXTO (3-8s): Una cafetería, dos horas, cero equipo extra.\nVALOR (8-28s): Luz lateral rasante para la crema · lavalier pegado a la máquina · 60fps para el vertido.\nCTA (28-34s): ¿Quieres el preset de color? Comenta CAFÉ.",
      cta: "Comenta CAFÉ", link: "", metricas: { views: 48200, likes: 3100, comentarios: 212, compartidos: 640, guardados: 1180, retencion: 41, seguidores: 210 },
      notas: "El plano del vertido a 60fps fue el que retuvo. El CTA con palabra clave trajo 190 comentarios.", creado: 1755000000000, actualizado: 1755400000000 },
    { id: "ej-p2", ejemplo: true, titulo: "3 errores al grabar comida con el celular", plataforma: "instagram", formato: "reel", pilar: "Educativo",
      hook: "3 errores al grabar comida con el celular (el segundo lo hace todo el mundo)", hookTipo: "lista", fecha: "2026-08-21", estado: "publicado", duracion: 41,
      guion: "HOOK: 3 errores al grabar comida con el celular.\n1. Luz de techo (sombras en el plato).\n2. Zoom digital en vez de acercarte.\n3. Grabar sin limpiar el lente.\nCTA: Guárdalo para tu próxima grabación.",
      cta: "Guárdalo", metricas: { views: 12300, likes: 760, comentarios: 44, compartidos: 120, guardados: 510, retencion: 36, seguidores: 38 },
      notas: "Buen ratio de guardados. Las listas funcionan mejor en Instagram que en TikTok.", creado: 1755400000000, actualizado: 1755800000000 },
    { id: "ej-p3", ejemplo: true, titulo: "Lo que nadie te dice de vivir de hacer videos", plataforma: "tiktok", formato: "reel", pilar: "Historia personal",
      hook: "Lo que nadie te dice de vivir de hacer videos para marcas", hookTipo: "historia", fecha: "2026-08-26", estado: "publicado", duracion: 52,
      guion: "HOOK: Lo que nadie te dice de vivir de hacer videos para marcas.\nHISTORIA: El primer cliente pagó 150 mil por 4 reels. Hoy ese mismo trabajo vale 10 veces más y el equipo es casi el mismo.\nGIRO: Lo que cambió no fue la cámara.\nCTA: Sígueme si estás empezando.",
      cta: "Sígueme", metricas: { views: 91500, likes: 6800, comentarios: 410, compartidos: 1500, guardados: 2100, retencion: 47, seguidores: 520 },
      notas: "Mejor pieza del mes. El giro a mitad (“no fue la cámara”) disparó comentarios.", creado: 1756000000000, actualizado: 1756300000000 },
    { id: "ej-p4", ejemplo: true, titulo: "Deja de poner música trending en todo", plataforma: "tiktok", formato: "reel", pilar: "Educativo",
      hook: "Deja de poner música trending en todos tus reels. Esto es lo que funciona.", hookTipo: "contrarian", fecha: "2026-09-02", estado: "publicado", duracion: 29,
      guion: "HOOK: Deja de poner música trending en todos tus reels.\nVALOR: El sonido real vende más que la canción: el vertido, el corte, el sartén.\nDEMO: Mismo clip, con música vs. con ASMR.\nCTA: ¿Cuál te retuvo más? Comenta 1 o 2.",
      cta: "Comenta 1 o 2", metricas: { views: 27400, likes: 1900, comentarios: 305, compartidos: 380, guardados: 640, retencion: 39, seguidores: 95 },
      notas: "La comparación A/B genera comentarios de opinión.", creado: 1756600000000, actualizado: 1756900000000 },
    { id: "ej-p5", ejemplo: true, titulo: "POV: el cliente pide que se vea premium", plataforma: "instagram", formato: "reel", pilar: "Humor",
      hook: "POV: el cliente dice “que se vea premium” y te manda una foto con flash", hookTipo: "pov", fecha: "2026-09-06", estado: "publicado", duracion: 18,
      guion: "POV con sketch corto: el mensaje del cliente, la cara, el antes/después de la foto con flash a la foto con luz lateral.",
      cta: "Etiqueta a un cliente", metricas: { views: 33900, likes: 2600, comentarios: 180, compartidos: 910, guardados: 330, retencion: 58, seguidores: 140 },
      notas: "Retención altísima por lo corto. Compartidos por identificación.", creado: 1757000000000, actualizado: 1757200000000 },
    { id: "ej-p6", ejemplo: true, titulo: "Un día de rodaje en la carnicería", plataforma: "youtube", formato: "largo", pilar: "Detrás de cámaras",
      hook: "Grabé 12 piezas de contenido en una carnicería en un solo día. Así lo planeé.", hookTipo: "resultado", fecha: "2026-08-12", estado: "publicado", duracion: 486,
      guion: "Vlog de rodaje: plan de 2 sesiones al mes, lista de planos, equipo (A7V, Hollyland, Ulanzi), edición por lotes.",
      cta: "Suscríbete", metricas: { views: 4100, likes: 260, comentarios: 38, compartidos: 22, guardados: 0, retencion: 31, seguidores: 60 },
      notas: "Formato largo: menos views pero comentarios de mucha calidad (preguntas de negocio).", creado: 1754800000000, actualizado: 1755000000000 },
    { id: "ej-p7", ejemplo: true, titulo: "Detrás de cámaras: sesión en la finca", plataforma: "tiktok", formato: "reel", pilar: "Detrás de cámaras",
      hook: "Subimos a 1.800 metros a grabar café. Esto fue lo que salió mal.", hookTipo: "historia", fecha: "2026-09-15", estado: "programado", duracion: 38,
      guion: "HOOK: Subimos a 1.800 metros a grabar café. Esto fue lo que salió mal.\nHISTORIA: la neblina tapó la finca a las 7am → cambiamos el plan: macro de granos y manos.\nVALOR: siempre ten un plan B de planos cerrados.\nCTA: Sígueme para la parte 2.",
      cta: "Parte 2", metricas: {}, notas: "", creado: 1757400000000, actualizado: 1757500000000 },
    { id: "ej-p8", ejemplo: true, titulo: "¿Cuánto cobrar por un reel?", plataforma: "tiktok", formato: "reel", pilar: "Negocio",
      hook: "¿Cuánto cobrar por un reel? Te muestro mi tabla real.", hookTipo: "pregunta", fecha: "2026-09-17", estado: "editado", duracion: 45,
      guion: "HOOK: ¿Cuánto cobrar por un reel?\nVALOR: 3 rangos según entregables (solo edición / grabación + edición / paquete mensual).\nGIRO: el error no es el precio, es no cobrar el guion.\nCTA: Comenta TABLA y te la mando.",
      cta: "Comenta TABLA", metricas: {}, notas: "", creado: 1757500000000, actualizado: 1757600000000 },
    { id: "ej-p9", ejemplo: true, titulo: "Mi setup de luz de 40W", plataforma: "instagram", formato: "carrusel", pilar: "Educativo",
      hook: "Con esta luz de 40W grabo todo. 5 posiciones que uso siempre.", hookTipo: "lista", fecha: "2026-09-19", estado: "guion", duracion: 0,
      guion: "Carrusel de 6 láminas: portada + 5 posiciones (lateral, rasante, contraluz, rebotada, cenital) con foto de ejemplo.",
      cta: "Guarda el carrusel", metricas: {}, notas: "", creado: 1757600000000, actualizado: 1757600000000 },
    { id: "ej-p10", ejemplo: true, titulo: "Antes / después: color en S-Cinetone", plataforma: "tiktok", formato: "reel", pilar: "Educativo",
      hook: "", hookTipo: "antes", fecha: "2026-09-22", estado: "idea", duracion: 0,
      guion: "Mismo clip: perfil estándar vs S-Cinetone con un ajuste de 30 segundos.", cta: "", metricas: {}, notas: "", creado: 1757700000000, actualizado: 1757700000000 },
  ],
  inspiracion: [
    { id: "ej-i1", ejemplo: true, autor: "@barista.ejemplo", plataforma: "tiktok", link: "", nicho: "Café de especialidad", views: 2400000, likes: 310000,
      hook: "Llevo 10 años haciendo café y este error lo cometen hasta los baristas", hookTipo: "error", estado: "analizado",
      guion: "Llevo 10 años haciendo café y este error lo cometen hasta los baristas. Muelen antes de calentar el agua. Mira la diferencia en la crema… (demo con dos tazas) … Ahora tú: ¿cuál huele mejor? Guarda esto para tu próximo café.",
      estructura: [
        { parte: "Hook", segundos: "0-3", texto: "Autoridad (10 años) + error que cometen “hasta los baristas”." },
        { parte: "Contexto", segundos: "3-7", texto: "Nombra el error sin explicarlo todavía: genera espera." },
        { parte: "Valor", segundos: "7-22", texto: "Demo visual A/B con dos tazas; la diferencia se ve, no se explica." },
        { parte: "Giro", segundos: "22-27", texto: "Pregunta abierta al espectador (“¿cuál huele mejor?”)." },
        { parte: "CTA", segundos: "27-31", texto: "Guardar para el próximo café: CTA de utilidad, no de seguir." },
      ],
      porque: ["Autoridad concreta en 2 palabras (10 años).", "La demo A/B convierte una opinión en algo visible.", "El error es pequeño y corregible: el espectador siente que gana algo.", "CTA de guardar = señal fuerte para el algoritmo."],
      miVersion: "Misma estructura con el vertido del café en Forestal: “este error lo cometen hasta las cafeterías” → demo con luz de techo vs luz lateral.",
      variantes: ["Llevo 6 años grabando comida y este error lo cometen hasta los restaurantes", "Hasta los chefs cometen este error cuando graban su plato", "10 años haciendo videos para marcas y este error lo sigo viendo"],
      etiquetas: ["A/B", "autoridad", "demo"], creado: 1756500000000 },
    { id: "ej-i2", ejemplo: true, autor: "@carniceria.ejemplo", plataforma: "instagram", link: "", nicho: "Carnes / parrilla", views: 890000, likes: 74000,
      hook: "No compres este corte si no vas a hacer esto", hookTipo: "contrarian", estado: "analizado",
      guion: "No compres este corte si no vas a hacer esto. (corte en tabla) La punta de anca necesita reposar 10 minutos después del fuego, si la cortas antes pierdes todo el jugo. Mira. (corte con jugo) Así se hace en Santander.",
      estructura: [
        { parte: "Hook", segundos: "0-3", texto: "Prohibición condicional: “no compres… si no…”." },
        { parte: "Valor", segundos: "3-15", texto: "Una sola regla (reposar 10 min) explicada con el producto en mano." },
        { parte: "Giro", segundos: "15-20", texto: "Prueba visual: el jugo al cortar." },
        { parte: "CTA", segundos: "20-24", texto: "Identidad regional: “así se hace en Santander” invita a compartir." },
      ],
      porque: ["Un solo consejo, fácil de recordar.", "El producto es el protagonista todo el tiempo.", "Orgullo regional = compartidos."],
      miVersion: "Para Carnes Manzanares: “No compres esta punta de anca si no vas a hacer esto” con el maestro carnicero explicando el reposo.",
      variantes: ["No grabes tu plato si no vas a hacer esto", "No compres una luz si no vas a hacer esto primero", "No publiques tu reel si no hiciste esto"],
      etiquetas: ["regla única", "producto", "regional"], creado: 1756800000000 },
    { id: "ej-i3", ejemplo: true, autor: "@creador.ejemplo", plataforma: "tiktok", link: "", nicho: "Marca personal / negocios", views: 1300000, likes: 150000,
      hook: "Gané mi primer millón con videos y esto es lo que haría distinto", hookTipo: "historia", estado: "por-analizar",
      guion: "(pegar aquí la transcripción o el caption para analizarlo)", estructura: [], porque: [], miVersion: "", variantes: [], etiquetas: ["historia", "negocio"], creado: 1757300000000 },
    { id: "ej-i4", ejemplo: true, autor: "@cafe.ejemplo", plataforma: "instagram", link: "", nicho: "Café de especialidad", views: 560000, likes: 41000,
      hook: "POV: llegas a la cafetería y el barista sabe tu nombre", hookTipo: "pov", estado: "usado",
      guion: "POV sin diálogo: entra el cliente, el barista sonríe y empieza a preparar sin preguntar. Texto en pantalla: “el café de siempre”.",
      estructura: [
        { parte: "Hook", segundos: "0-2", texto: "POV reconocible + texto en pantalla." },
        { parte: "Valor", segundos: "2-12", texto: "Sin diálogo, solo gesto y sonido ambiente." },
        { parte: "CTA", segundos: "12-15", texto: "Texto: “etiqueta a quien te acompaña”." },
      ],
      porque: ["Emoción de pertenencia en 15 segundos.", "Sin voz = funciona sin sonido.", "CTA de etiquetar trae alcance."],
      miVersion: "Hecho para Forestal en septiembre: POV del cliente habitual con la barista.", variantes: [], etiquetas: ["POV", "emocional"], creado: 1755500000000 },
    { id: "ej-i5", ejemplo: true, autor: "@video.ejemplo", plataforma: "youtube", link: "", nicho: "Producción de video", views: 410000, likes: 22000,
      hook: "Esta luz de 60 dólares se ve mejor que mi luz de 600", hookTipo: "antes", estado: "por-analizar",
      guion: "(pegar aquí la transcripción o el caption para analizarlo)", estructura: [], porque: [], miVersion: "", variantes: [], etiquetas: ["equipo", "comparación"], creado: 1757500000000 },
  ],
  seguidores: [
    { fecha: "2026-06-01", plataforma: "tiktok", total: 2810 }, { fecha: "2026-07-01", plataforma: "tiktok", total: 3120 },
    { fecha: "2026-08-01", plataforma: "tiktok", total: 3480 }, { fecha: "2026-09-01", plataforma: "tiktok", total: 4210 }, { fecha: "2026-09-13", plataforma: "tiktok", total: 4390 },
    { fecha: "2026-06-01", plataforma: "instagram", total: 1810 }, { fecha: "2026-07-01", plataforma: "instagram", total: 1890 },
    { fecha: "2026-08-01", plataforma: "instagram", total: 1960 }, { fecha: "2026-09-01", plataforma: "instagram", total: 2140 }, { fecha: "2026-09-13", plataforma: "instagram", total: 2205 },
  ],
};
